export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const SET_FILTERS = 'SET_FILTERS'
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE'

export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM'
export const TOGGLE_TODO_ITEM_STATUS = 'TOGGLE_TODO_ITEM_STATUS'
